<?php
/*
define('DB_SERVER','localhost');
define('DB_USERNAME','root');
define('DB_PASSWORD','');
define('DB_DATABASE','test');

define('DB_SERVER','mysql01.manashosting.biz');
define('DB_USERNAME','pavan_pepsy');
define('DB_PASSWORD','28pepsy1986');
define('DB_DATABASE','pavan_feedback');

define('DB_SERVER','localhost');
define('DB_USERNAME','pavanrat_pavan');
define('DB_PASSWORD','28pepsy1998');
define('DB_DATABASE','pavanrat_main');
*/
define('DB_SERVER','localhost');
define('DB_USERNAME','pavanrat_pavan');
define('DB_PASSWORD','28pepsy1998');
define('DB_DATABASE','pavanrat_main');
define('USER_TABLE','users');
define('INV_TABLE','invheader');
define('CLIENT','clients');
define('ORDERS','invlines');
define('PRODUCT','product');
define('CONTACT','contacts');
define('MAILTO','sales@gurbaksishgroup.com');
define('MAILCC','gurbaksishgulati@yahoo.com');
define('OWNER_EMAIL','pavanratnakar@gmail.com');
define('ADMIN_EMAIL','sonalb256@gmail.com');
define('RECEIPT_NAME','Sunitha');
?>